#!/bin/bash


echo "Compiling sudoku.c ---> sudoku.exe" &&
cd contrib/sudoku &&
sudo make install &&
cd ../.. &&
echo "ICS OS -> sudo make install" &&
sudo make install &&
qemu-system-i386 -fda ics-os-floppy.img &&
echo "STARTING ICS-OS"